# Generated by Django 5.2.4 on 2025-07-26 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtosalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='photo/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_ed', models.DateTimeField(auto_now_add=True)),
                ('update_ed', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('year', models.DateTimeField()),
                ('color', models.CharField(max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.brand')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configapp.avtosalon')),
            ],
        ),
    ]
